# Generated by Django 6.0.6 on 2026-06-06 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Formative Task, Mid-Term Test, End of Term Exam', max_length=50)),
                ('weight_percentage', models.DecimalField(decimal_places=2, help_text='The percentage weight this category holds towards the final term mark.', max_digits=5)),
                ('is_formative', models.BooleanField(default=True, help_text='Check if this is a continuous/formative assessment.')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField()),
                ('term_number', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'unique_together': {('academic_year', 'term_number')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., February Fractions Quiz, Term 1 Final', max_length=150)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='The maximum achievable raw score for this specific task.', max_digits=5)),
                ('date_administered', models.DateField()),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.academicterm')),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('teacher_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='assessments.assessmentrecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'assessment')},
            },
        ),
    ]
