# Generated by Django 6.0.6 on 2026-06-06 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent (Unexcused)'), ('EXCUSED', 'Absent (Excused/Sick)'), ('LATE', 'Late')], default='PRESENT', max_length=10)),
                ('sms_alert_sent', models.BooleanField(default=False, help_text='Tracks whether the automated SMS has already been dispatched for this absence.')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='school.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
